[profile]
name-template = "{{profile}}"

[profile.matrix]
profile = ["latest"]

[build.".+"]
image-name-template = "ghcr.io/cyqsimon/dev-container-codex-rust"
image-tag-template = "{{profile.name}}"
platforms = ["linux/amd64", "linux/arm64"]
